#!/usr/bin/env ruby
#
# replace the epoch seconds with something a bit more readable

ARGF.each do |line|
    if line =~ /^\[(\d{10})\] (.*)/
      t = Time.at $1.to_i
      puts "#{t.month}/#{t.day} #{t.hour}:#{t.min}:#{t.sec} #{$2}" 
    end
end
